# Generated by Django 5.0.7 on 2024-10-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceimage',
            old_name='post',
            new_name='service',
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
