# Generated by Django 5.0.7 on 2024-10-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_post_serviceimage_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
    ]
