# Generated by Django 5.0.7 on 2024-10-03 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=250)),
                ('degree', models.CharField(choices=[('AS', 'AS'), ('AA', 'AA'), ('BA', 'BA'), ('BS', 'BS'), ('BSC', 'BSC'), ('BSE', 'BSE'), ('BFA', 'BFA'), ('BBA', 'BBA'), ('MA', 'MA'), ('MS', 'MS'), ('MBA', 'MBA'), ('MFA', 'MFA'), ('PHD', 'PHD'), ('EDD', 'EDD'), ('JD', 'JD'), ('MD', 'MD'), ('DO', 'DO'), ('DPT', 'DPT')], max_length=250)),
                ('field_of_study', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
