# Generated by Django 5.0.7 on 2024-10-04 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('education', '0002_alter_education_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
    ]
