DEGREE_TYPE = [
    ("AS", "AS"),
    ("AA", "AA"),
    ("BA", "BA"),
    ("BS", "BS"),
    ("BSC", "BSC"),
    ("BSE", "BSE"),
    ("BFA", "BFA"),
    ("BBA", "BBA"),
    ("MA", "MA"),
    ("MS", "MS"),
    ("MBA", "MBA"),
    ("MFA", "MFA"),
    ("PHD", "PHD"),
    ("EDD", "EDD"),
    ("JD", "JD"),
    ("MD", "MD"),
    ("DO", "DO"),
    ("DPT", "DPT"),
]
