# Generated by Django 5.0.7 on 2024-10-03 10:57

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('doctors', '0001_initial'),
        ('staffs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('cover_img', models.ImageField(default='', upload_to=core.utils.user_directory_path)),
                ('profile_img', models.ImageField(default='', upload_to=core.utils.user_directory_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=17)),
                ('opening_hours', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('doctors', models.ManyToManyField(related_name='hospitals', to='staffs.staff')),
                ('specialties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.specialization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('zip_code', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='hospitals.hospital')),
            ],
        ),
    ]
