# Generated by Django 5.0.7 on 2024-10-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='staffs',
            field=models.ManyToManyField(related_name='hospitals', to='staffs.staff'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(related_name='hospitals', to='doctors.doctor'),
        ),
    ]
