# Generated by Django 5.0.7 on 2024-10-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_staffs_alter_hospital_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='slug',
        ),
    ]
