# Generated by Django 5.0.7 on 2024-10-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0004_alter_hospital_created_at_alter_location_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='specialties',
        ),
        migrations.AddField(
            model_name='hospital',
            name='specialties',
            field=models.ManyToManyField(to='doctors.specialization'),
        ),
    ]
