# Generated by Django 5.0.7 on 2024-10-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0005_remove_hospital_specialties_hospital_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(to='doctors.doctor'),
        ),
    ]
