# Generated by Django 5.0.7 on 2024-10-04 19:52

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0006_alter_hospital_doctors'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.user_directory_path),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(blank=True, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.user_directory_path),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='staffs',
            field=models.ManyToManyField(blank=True, related_name='hospitals', to='staffs.staff'),
        ),
    ]
