# Generated by Django 5.0.7 on 2024-10-07 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0009_alter_location_city_alter_location_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDoctorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_add_doctor_requests', to='hospitals.hospital')),
                ('to_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_job_requests', to='doctors.doctor')),
            ],
            options={
                'unique_together': {('from_hospital', 'to_doctor')},
            },
        ),
    ]
