# Generated by Django 5.0.7 on 2024-10-03 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0002_hospital_staffs_alter_hospital_doctors'),
        ('services', '0002_rename_post_serviceimage_service_and_more'),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctors', models.ManyToManyField(related_name='departments', to='doctors.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospitals.hospital')),
                ('services', models.ManyToManyField(related_name='departments', to='services.service')),
                ('staffs', models.ManyToManyField(related_name='departments', to='staffs.staff')),
            ],
        ),
    ]
