# Generated by Django 5.0.7 on 2024-10-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
    ]
